[package]
name = "dora-sema-fuzzer"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dora-frontend = { path = "../dora-frontend", version = "0.0.2" }
afl = "*"
