#!/bin/sh

set -e

cd lib/dora-parser
cargo build --release
cargo test --release
cd ../..

cargo build --release && cargo test --release && ruby tester.rb --release $@
cargo run lib/boots/compile.dora
cargo run -- test lib/boots/compile.dora
