#[derive(Clone, Copy, Debug)]
pub enum Intrinsic {
    ArrayNewOfSize,
    ArrayWithValues,
    ArrayLen,
    ArrayGet,
    ArraySet,
    Unreachable,
    FatalError,
    UnsafeKillRefs,
    Assert,
    Debug,
    StrLen,
    StrGet,
    BoolEq,
    BoolNot,
    BoolToInt32,
    BoolToInt64,
    UInt8Eq,
    UInt8Cmp,
    UInt8ToChar,
    UInt8ToInt32,
    UInt8ToInt64,
    CharEq,
    CharCmp,
    CharToInt32,
    CharToInt64,
    Int32ToUInt8,
    Int32ToCharUnchecked,
    Int32ToInt64,
    Int32ToFloat32,
    Int32ToFloat64,
    ReinterpretInt32AsFloat32,
    EnumEq,
    EnumNe,
    Int32Eq,
    Int32Cmp,
    Int32CheckedAdd,
    Int32WrappingAdd,
    Int32CheckedSub,
    Int32WrappingSub,
    Int32CheckedMul,
    Int32WrappingMul,
    Int32OverflowingAdd,
    Int32OverflowingSub,
    Int32OverflowingMul,
    Int32OverflowingDiv,
    Int32OverflowingMod,
    Int32CheckedDiv,
    Int32CheckedMod,
    Int32Or,
    Int32And,
    Int32Xor,
    Int32Shl,
    Int32Sar,
    Int32Shr,
    Int32RotateLeft,
    Int32RotateRight,
    Int32Not,
    Int32CheckedNeg,
    Int32WrappingNeg,
    Int32OverflowingNeg,
    Int32CountZeroBits,
    Int32CountOneBits,
    Int32CountZeroBitsLeading,
    Int32CountOneBitsLeading,
    Int32CountZeroBitsTrailing,
    Int32CountOneBitsTrailing,
    Int64ToInt32,
    Int64ToCharUnchecked,
    Int64ToUInt8,
    Int64ToFloat32,
    Int64ToFloat64,
    ReinterpretInt64AsFloat64,
    Int64Eq,
    Int64Cmp,
    Int64CheckedAdd,
    Int64WrappingAdd,
    Int64CheckedSub,
    Int64WrappingSub,
    Int64CheckedMul,
    Int64WrappingMul,
    Int64OverflowingAdd,
    Int64OverflowingSub,
    Int64OverflowingMul,
    Int64OverflowingDiv,
    Int64OverflowingMod,
    Int64CheckedDiv,
    Int64CheckedMod,
    Int64Or,
    Int64And,
    Int64Xor,
    Int64Shl,
    Int64Sar,
    Int64Shr,
    Int64RotateLeft,
    Int64RotateRight,
    Int64Not,
    Int64CheckedNeg,
    Int64WrappingNeg,
    Int64OverflowingNeg,
    Int64CountZeroBits,
    Int64CountOneBits,
    Int64CountZeroBitsLeading,
    Int64CountOneBitsLeading,
    Int64CountZeroBitsTrailing,
    Int64CountOneBitsTrailing,
    Float32ToInt32,
    Float32ToInt64,
    PromoteFloat32ToFloat64,
    ReinterpretFloat32AsInt32,
    Float32Eq,
    Float32Cmp,
    Float32Add,
    Float32Sub,
    Float32Mul,
    Float32Div,
    Float32Neg,
    Float32Abs,
    Float32IsNan,
    Float32RoundToZero,
    Float32RoundUp,
    Float32RoundDown,
    Float32RoundHalfEven,
    Float32Sqrt,
    Float64ToInt32,
    Float64ToInt64,
    DemoteFloat64ToFloat32,
    ReinterpretFloat64AsInt64,
    Float64Eq,
    Float64Cmp,
    Float64Add,
    Float64Sub,
    Float64Mul,
    Float64Div,
    Float64Neg,
    Float64Abs,
    Float64IsNan,
    Float64RoundToZero,
    Float64RoundUp,
    Float64RoundDown,
    Float64RoundHalfEven,
    Float64Sqrt,
    OptionGetOrPanic,
    OptionIsNone,
    OptionIsSome,
    AtomicInt32Get,
    AtomicInt32Set,
    AtomicInt32Exchange,
    AtomicInt32CompareExchange,
    AtomicInt32FetchAdd,
    AtomicInt64Get,
    AtomicInt64Set,
    AtomicInt64Exchange,
    AtomicInt64CompareExchange,
    AtomicInt64FetchAdd,
    ThreadCurrent,
}

pub const STDLIB_INTRINSICS: &[(&'static str, Intrinsic)] = &[
    ("std::unreachable", Intrinsic::Unreachable),
    ("std::fatal_error", Intrinsic::FatalError),
    ("std::assert", Intrinsic::Assert),
    ("std::debug", Intrinsic::Debug),
    ("std::unsafe_kill_refs", Intrinsic::UnsafeKillRefs),
    (
        "std::traits::Equals for std::primitives::Bool#equals",
        Intrinsic::BoolEq,
    ),
    (
        "std::traits::Not for std::primitives::Bool#not",
        Intrinsic::BoolNot,
    ),
    ("std::primitives::Bool#to_int32", Intrinsic::BoolToInt32),
    ("std::primitives::Bool#to_int64", Intrinsic::BoolToInt64),
    (
        "std::traits::Equals for std::primitives::UInt8#equals",
        Intrinsic::UInt8Eq,
    ),
    (
        "std::traits::Comparable for std::primitives::UInt8#cmp",
        Intrinsic::UInt8Cmp,
    ),
    ("std::primitives::UInt8#to_char", Intrinsic::UInt8ToChar),
    ("std::primitives::UInt8#to_int32", Intrinsic::UInt8ToInt32),
    ("std::primitives::UInt8#to_int64", Intrinsic::UInt8ToInt64),
    (
        "std::traits::Equals for std::primitives::Char#equals",
        Intrinsic::CharEq,
    ),
    (
        "std::traits::Comparable for std::primitives::Char#cmp",
        Intrinsic::CharCmp,
    ),
    ("std::primitives::Char#to_int32", Intrinsic::CharToInt32),
    ("std::primitives::Char#to_int64", Intrinsic::CharToInt64),
    (
        "std::traits::Equals for std::primitives::Int32#equals",
        Intrinsic::Int32Eq,
    ),
    (
        "std::traits::Comparable for std::primitives::Int32#cmp",
        Intrinsic::Int32Cmp,
    ),
    (
        "std::traits::Add for std::primitives::Int32#add",
        Intrinsic::Int32CheckedAdd,
    ),
    (
        "std::traits::Sub for std::primitives::Int32#sub",
        Intrinsic::Int32CheckedSub,
    ),
    (
        "std::traits::Mul for std::primitives::Int32#mul",
        Intrinsic::Int32CheckedMul,
    ),
    (
        "std::traits::Div for std::primitives::Int32#div",
        Intrinsic::Int32CheckedDiv,
    ),
    (
        "std::traits::Mod for std::primitives::Int32#modulo",
        Intrinsic::Int32CheckedMod,
    ),
    (
        "std::traits::BitOr for std::primitives::Int32#bitor",
        Intrinsic::Int32Or,
    ),
    (
        "std::traits::BitAnd for std::primitives::Int32#bitand",
        Intrinsic::Int32And,
    ),
    (
        "std::traits::BitXor for std::primitives::Int32#bitxor",
        Intrinsic::Int32Xor,
    ),
    (
        "std::traits::Shl for std::primitives::Int32#shl",
        Intrinsic::Int32Shl,
    ),
    (
        "std::traits::Shr for std::primitives::Int32#shr",
        Intrinsic::Int32Shr,
    ),
    (
        "std::traits::Sar for std::primitives::Int32#sar",
        Intrinsic::Int32Sar,
    ),
    (
        "std::traits::Not for std::primitives::Int32#not",
        Intrinsic::Int32Not,
    ),
    (
        "std::traits::Neg for std::primitives::Int32#neg",
        Intrinsic::Int32CheckedNeg,
    ),
    (
        "std::primitives::Int32#wrapping_neg",
        Intrinsic::Int32WrappingNeg,
    ),
    (
        "std::primitives::Int32#overflowing_neg",
        Intrinsic::Int32OverflowingNeg,
    ),
    (
        "std::primitives::Int32#count_zero_bits_leading",
        Intrinsic::Int32CountZeroBitsLeading,
    ),
    (
        "std::primitives::Int32#count_zero_bits_trailing",
        Intrinsic::Int32CountZeroBitsTrailing,
    ),
    (
        "std::primitives::Int32#count_one_bits_leading",
        Intrinsic::Int32CountOneBitsLeading,
    ),
    (
        "std::primitives::Int32#count_one_bits_trailing",
        Intrinsic::Int32CountOneBitsTrailing,
    ),
    (
        "std::primitives::Int32#count_zero_bits",
        Intrinsic::Int32CountZeroBits,
    ),
    (
        "std::primitives::Int32#count_one_bits",
        Intrinsic::Int32CountOneBits,
    ),
    (
        "std::primitives::Int32#rotate_left",
        Intrinsic::Int32RotateLeft,
    ),
    (
        "std::primitives::Int32#rotate_right",
        Intrinsic::Int32RotateRight,
    ),
    (
        "std::primitives::Int32#wrapping_add",
        Intrinsic::Int32WrappingAdd,
    ),
    (
        "std::primitives::Int32#wrapping_sub",
        Intrinsic::Int32WrappingSub,
    ),
    (
        "std::primitives::Int32#wrapping_mul",
        Intrinsic::Int32WrappingMul,
    ),
    (
        "std::primitives::Int32#overflowing_add",
        Intrinsic::Int32OverflowingAdd,
    ),
    (
        "std::primitives::Int32#overflowing_sub",
        Intrinsic::Int32OverflowingSub,
    ),
    (
        "std::primitives::Int32#overflowing_mul",
        Intrinsic::Int32OverflowingMul,
    ),
    (
        "std::primitives::Int32#overflowing_div",
        Intrinsic::Int32OverflowingDiv,
    ),
    (
        "std::primitives::Int32#overflowing_mod",
        Intrinsic::Int32OverflowingMod,
    ),
    ("std::primitives::Int32#to_uint8", Intrinsic::Int32ToUInt8),
    (
        "std::primitives::Int32#to_char_unchecked",
        Intrinsic::Int32ToCharUnchecked,
    ),
    ("std::primitives::Int32#to_int64", Intrinsic::Int32ToInt64),
    (
        "std::primitives::Int32#to_float32",
        Intrinsic::Int32ToFloat32,
    ),
    (
        "std::primitives::Int32#to_float64",
        Intrinsic::Int32ToFloat64,
    ),
    (
        "std::primitives::Int32#as_float32",
        Intrinsic::ReinterpretInt32AsFloat32,
    ),
    (
        "std::traits::Equals for std::primitives::Int64#equals",
        Intrinsic::Int64Eq,
    ),
    (
        "std::traits::Comparable for std::primitives::Int64#cmp",
        Intrinsic::Int64Cmp,
    ),
    (
        "std::traits::Add for std::primitives::Int64#add",
        Intrinsic::Int64CheckedAdd,
    ),
    (
        "std::traits::Sub for std::primitives::Int64#sub",
        Intrinsic::Int64CheckedSub,
    ),
    (
        "std::traits::Mul for std::primitives::Int64#mul",
        Intrinsic::Int64CheckedMul,
    ),
    (
        "std::traits::Div for std::primitives::Int64#div",
        Intrinsic::Int64CheckedDiv,
    ),
    (
        "std::traits::Mod for std::primitives::Int64#modulo",
        Intrinsic::Int64CheckedMod,
    ),
    (
        "std::traits::BitOr for std::primitives::Int64#bitor",
        Intrinsic::Int64Or,
    ),
    (
        "std::traits::BitAnd for std::primitives::Int64#bitand",
        Intrinsic::Int64And,
    ),
    (
        "std::traits::BitXor for std::primitives::Int64#bitxor",
        Intrinsic::Int64Xor,
    ),
    (
        "std::traits::Shl for std::primitives::Int64#shl",
        Intrinsic::Int64Shl,
    ),
    (
        "std::traits::Shr for std::primitives::Int64#shr",
        Intrinsic::Int64Shr,
    ),
    (
        "std::traits::Sar for std::primitives::Int64#sar",
        Intrinsic::Int64Sar,
    ),
    (
        "std::traits::Not for std::primitives::Int64#not",
        Intrinsic::Int64Not,
    ),
    (
        "std::traits::Neg for std::primitives::Int64#neg",
        Intrinsic::Int64CheckedNeg,
    ),
    (
        "std::primitives::Int64#wrapping_neg",
        Intrinsic::Int64WrappingNeg,
    ),
    (
        "std::primitives::Int64#overflowing_neg",
        Intrinsic::Int64OverflowingNeg,
    ),
    (
        "std::primitives::Int64#count_zero_bits_leading",
        Intrinsic::Int64CountZeroBitsLeading,
    ),
    (
        "std::primitives::Int64#count_zero_bits_trailing",
        Intrinsic::Int64CountZeroBitsTrailing,
    ),
    (
        "std::primitives::Int64#count_one_bits_leading",
        Intrinsic::Int64CountOneBitsLeading,
    ),
    (
        "std::primitives::Int64#count_one_bits_trailing",
        Intrinsic::Int64CountOneBitsTrailing,
    ),
    (
        "std::primitives::Int64#count_zero_bits",
        Intrinsic::Int64CountZeroBits,
    ),
    (
        "std::primitives::Int64#count_one_bits",
        Intrinsic::Int64CountOneBits,
    ),
    (
        "std::primitives::Int64#rotate_left",
        Intrinsic::Int64RotateLeft,
    ),
    (
        "std::primitives::Int64#rotate_right",
        Intrinsic::Int64RotateRight,
    ),
    (
        "std::primitives::Int64#wrapping_add",
        Intrinsic::Int64WrappingAdd,
    ),
    (
        "std::primitives::Int64#wrapping_sub",
        Intrinsic::Int64WrappingSub,
    ),
    (
        "std::primitives::Int64#wrapping_mul",
        Intrinsic::Int64WrappingMul,
    ),
    (
        "std::primitives::Int64#overflowing_add",
        Intrinsic::Int64OverflowingAdd,
    ),
    (
        "std::primitives::Int64#overflowing_sub",
        Intrinsic::Int64OverflowingSub,
    ),
    (
        "std::primitives::Int64#overflowing_mul",
        Intrinsic::Int64OverflowingMul,
    ),
    (
        "std::primitives::Int64#overflowing_div",
        Intrinsic::Int64OverflowingDiv,
    ),
    (
        "std::primitives::Int64#overflowing_mod",
        Intrinsic::Int64OverflowingMod,
    ),
    ("std::primitives::Int64#to_uint8", Intrinsic::Int64ToUInt8),
    ("std::primitives::Int64#to_int32", Intrinsic::Int64ToInt32),
    (
        "std::primitives::Int64#to_char_unchecked",
        Intrinsic::Int64ToCharUnchecked,
    ),
    (
        "std::primitives::Int64#to_float32",
        Intrinsic::Int64ToFloat32,
    ),
    (
        "std::primitives::Int64#to_float64",
        Intrinsic::Int64ToFloat64,
    ),
    (
        "std::primitives::Int64#as_float64",
        Intrinsic::ReinterpretInt64AsFloat64,
    ),
    (
        "std::traits::Equals for std::primitives::Float32#equals",
        Intrinsic::Float32Eq,
    ),
    (
        "std::traits::Comparable for std::primitives::Float32#cmp",
        Intrinsic::Float32Cmp,
    ),
    (
        "std::traits::Add for std::primitives::Float32#add",
        Intrinsic::Float32Add,
    ),
    (
        "std::traits::Sub for std::primitives::Float32#sub",
        Intrinsic::Float32Sub,
    ),
    (
        "std::traits::Mul for std::primitives::Float32#mul",
        Intrinsic::Float32Mul,
    ),
    (
        "std::traits::Div for std::primitives::Float32#div",
        Intrinsic::Float32Div,
    ),
    (
        "std::traits::Neg for std::primitives::Float32#neg",
        Intrinsic::Float32Neg,
    ),
    ("std::primitives::Float32#abs", Intrinsic::Float32Abs),
    ("std::primitives::Float32#is_nan", Intrinsic::Float32IsNan),
    (
        "std::primitives::Float32#round_to_zero",
        Intrinsic::Float32RoundToZero,
    ),
    (
        "std::primitives::Float32#round_up",
        Intrinsic::Float32RoundUp,
    ),
    (
        "std::primitives::Float32#round_down",
        Intrinsic::Float32RoundDown,
    ),
    (
        "std::primitives::Float32#round_half_even",
        Intrinsic::Float32RoundHalfEven,
    ),
    ("std::primitives::Float32#sqrt", Intrinsic::Float32Sqrt),
    (
        "std::primitives::Float32#to_int32",
        Intrinsic::Float32ToInt32,
    ),
    (
        "std::primitives::Float32#to_int64",
        Intrinsic::Float32ToInt64,
    ),
    (
        "std::primitives::Float32#to_float64",
        Intrinsic::PromoteFloat32ToFloat64,
    ),
    (
        "std::primitives::Float32#as_int32",
        Intrinsic::ReinterpretFloat32AsInt32,
    ),
    (
        "std::traits::Equals for std::primitives::Float64#equals",
        Intrinsic::Float64Eq,
    ),
    (
        "std::traits::Comparable for std::primitives::Float64#cmp",
        Intrinsic::Float64Cmp,
    ),
    (
        "std::traits::Add for std::primitives::Float64#add",
        Intrinsic::Float64Add,
    ),
    (
        "std::traits::Sub for std::primitives::Float64#sub",
        Intrinsic::Float64Sub,
    ),
    (
        "std::traits::Mul for std::primitives::Float64#mul",
        Intrinsic::Float64Mul,
    ),
    (
        "std::traits::Div for std::primitives::Float64#div",
        Intrinsic::Float64Div,
    ),
    (
        "std::traits::Neg for std::primitives::Float64#neg",
        Intrinsic::Float64Neg,
    ),
    ("std::primitives::Float64#abs", Intrinsic::Float64Abs),
    ("std::primitives::Float64#is_nan", Intrinsic::Float64IsNan),
    (
        "std::primitives::Float64#round_to_zero",
        Intrinsic::Float64RoundToZero,
    ),
    (
        "std::primitives::Float64#round_up",
        Intrinsic::Float64RoundUp,
    ),
    (
        "std::primitives::Float64#round_down",
        Intrinsic::Float64RoundDown,
    ),
    (
        "std::primitives::Float64#round_half_even",
        Intrinsic::Float64RoundHalfEven,
    ),
    ("std::primitives::Float64#sqrt", Intrinsic::Float64Sqrt),
    (
        "std::primitives::Float64#to_int32",
        Intrinsic::Float64ToInt32,
    ),
    (
        "std::primitives::Float64#to_int64",
        Intrinsic::Float64ToInt64,
    ),
    (
        "std::primitives::Float64#to_float32",
        Intrinsic::DemoteFloat64ToFloat32,
    ),
    (
        "std::primitives::Float64#as_int64",
        Intrinsic::ReinterpretFloat64AsInt64,
    ),
    ("std::string::String#size", Intrinsic::StrLen),
    ("std::string::String#get_byte", Intrinsic::StrGet),
    ("std::collections::Array#size", Intrinsic::ArrayLen),
    (
        "std::traits::IndexGet for std::collections::Array#get",
        Intrinsic::ArrayGet,
    ),
    (
        "std::traits::IndexSet for std::collections::Array#set",
        Intrinsic::ArraySet,
    ),
    (
        "std::collections::Array#unsafe_new",
        Intrinsic::ArrayNewOfSize,
    ),
    ("std::collections::Array#new", Intrinsic::ArrayWithValues),
    (
        "std::primitives::Option#get_or_panic",
        Intrinsic::OptionGetOrPanic,
    ),
    ("std::primitives::Option#is_none", Intrinsic::OptionIsNone),
    ("std::primitives::Option#is_some", Intrinsic::OptionIsSome),
    ("std::thread::AtomicInt32#get", Intrinsic::AtomicInt32Get),
    ("std::thread::AtomicInt32#set", Intrinsic::AtomicInt32Set),
    (
        "std::thread::AtomicInt32#exchange",
        Intrinsic::AtomicInt32Exchange,
    ),
    (
        "std::thread::AtomicInt32#compare_exchange",
        Intrinsic::AtomicInt32CompareExchange,
    ),
    (
        "std::thread::AtomicInt32#fetch_add",
        Intrinsic::AtomicInt32FetchAdd,
    ),
    ("std::thread::AtomicInt64#get", Intrinsic::AtomicInt64Get),
    ("std::thread::AtomicInt64#set", Intrinsic::AtomicInt64Set),
    (
        "std::thread::AtomicInt64#exchange",
        Intrinsic::AtomicInt64Exchange,
    ),
    (
        "std::thread::AtomicInt64#compare_exchange",
        Intrinsic::AtomicInt64CompareExchange,
    ),
    (
        "std::thread::AtomicInt64#fetch_add",
        Intrinsic::AtomicInt64FetchAdd,
    ),
    ("std::thread::Thread#current", Intrinsic::ThreadCurrent),
];
