use std::fs::File;
use std::io::Write;
use std::process::Command;

use crate::driver::flags::CompileArgs;
use crate::driver::start::{Result, compile_program, finish_vm};
use dora_runtime::{
    AotFunction, VM, VmFlags, VmMode, compile_program_functions, dora_entry_trampoline,
    execute_on_main, mangle_name, set_vm,
};

pub fn command_compile(args: CompileArgs) -> Result<()> {
    let prog = compile_program(&args.file, &args.common, true)?;

    let vm_flags = VmFlags {
        emit_asm: None,
        emit_asm_file: None,
        emit_asm_boots: false,
        emit_bytecode_compiler: None,
        emit_bytecode_boots: false,
        emit_compiler: false,
        emit_graph: None,
        emit_graph_after_each_pass: false,
        emit_stubs: false,
        enable_perf: false,
        always_boots: true,
        use_boots: None,
        omit_bounds_check: false,
        emit_debug: None,
        emit_debug_boots: false,
        emit_debug_native: false,
        emit_debug_compile: false,
        emit_debug_entry: false,
        gc_events: false,
        gc_stress: false,
        gc_stress_minor: false,
        gc_stress_in_lazy_compile: false,
        gc_stats: false,
        gc_verbose: false,
        gc_verify: false,
        gc_worker: 0,
        gc_young_size: None,
        gc_semi_ratio: None,
        gc: None,
        compiler: None,
        min_heap_size: None,
        max_heap_size: None,
        code_size: None,
        readonly_size: None,
        disable_tlab: false,
        disable_barrier: false,
        bootstrap_compiler: false,
        snapshot_on_oom: None,
    };

    let vm = VM::new(VmMode::Jit, prog, vm_flags, Vec::new());
    set_vm(&vm);
    vm.compile_boots_aot();

    let trampoline = dora_entry_trampoline::generate(&vm);
    let functions = execute_on_main(|| compile_program_functions(&vm));

    let asm_file = tempfile::Builder::new().suffix(".s").tempfile()?;

    {
        let mut f = File::create(asm_file.path())?;
        write_assembly(&mut f, &functions, &trampoline.code)?;
    }

    finish_vm(&vm);

    // Find the runtime static library next to the current executable.
    let exe_dir = std::env::current_exe()?
        .parent()
        .expect("no parent directory")
        .to_path_buf();
    let runtime_lib = exe_dir.join("libdora_runtime.a");

    if !runtime_lib.exists() {
        return Err(format!("runtime library not found at {}", runtime_lib.display()).into());
    }

    let status = Command::new("gcc")
        .arg(asm_file.path())
        .arg(&runtime_lib)
        .arg("-lpthread")
        .arg("-ldl")
        .arg("-lm")
        .arg("-o")
        .arg(&args.output)
        .status()?;

    if !status.success() {
        return Err("gcc failed".into());
    }

    Ok(())
}

fn write_assembly(
    f: &mut File,
    functions: &[AotFunction],
    trampoline: &[u8],
) -> std::io::Result<()> {
    writeln!(f, ".text")?;

    for func in functions {
        let label = mangle_name(&func.name);
        writeln!(f)?;
        writeln!(f, ".globl {}", label)?;
        writeln!(f, "{}:", label)?;

        for chunk in func.code.chunks(12) {
            let bytes: Vec<String> = chunk.iter().map(|b| format!("0x{:02x}", b)).collect();
            writeln!(f, "    .byte {}", bytes.join(", "))?;
        }

        // Emit relocations for direct call sites.
        // The offset in the relocation is the return address (after the call instruction).
        // For x64 call_rel32: the 4-byte operand starts at offset-4, so we relocate at offset-4.
        for reloc in &func.relocations {
            let reloc_offset = reloc.offset - 4;
            writeln!(
                f,
                "    .reloc {}+{}, R_X86_64_PC32, {} - 4",
                label, reloc_offset, reloc.target,
            )?;
        }
    }

    // Emit the dora entry trampoline (generated by dora_entry_trampoline::generate).
    // Signature: extern "C" fn(tld: usize, fct: *const u8) -> i32
    writeln!(f)?;
    writeln!(f, ".globl _dora_entry_trampoline")?;
    writeln!(f, "_dora_entry_trampoline:")?;
    for chunk in trampoline.chunks(12) {
        let bytes: Vec<String> = chunk.iter().map(|b| format!("0x{:02x}", b)).collect();
        writeln!(f, "    .byte {}", bytes.join(", "))?;
    }

    // Emit the main entry point that tail-calls dora_aot_main.
    writeln!(f)?;
    writeln!(f, ".globl main")?;
    writeln!(f, "main:")?;
    writeln!(f, "    jmp dora_aot_main")?;

    Ok(())
}
