#!/bin/bash

PROFILE=release

cargo build -p dora --profile "$PROFILE"
cargo build -p dora-language-server --profile "$PROFILE"

INSTALL_BIN_DIR="$HOME/.local/bin"
INSTALL_SHARE_DIR="$HOME/.local/share/dora"
INSTALL_PKGS_DIR="$INSTALL_SHARE_DIR/pkgs"

# Clean previous share install but avoid clobbering unrelated binaries.
rm -rf "$INSTALL_SHARE_DIR"
mkdir -p "$INSTALL_BIN_DIR"
mkdir -p "$INSTALL_PKGS_DIR"

cp "target/$PROFILE/dora" "$INSTALL_BIN_DIR"
cp "target/$PROFILE/dora-language-server" "$INSTALL_BIN_DIR"

cp -R pkgs/std "$INSTALL_PKGS_DIR"
cp -R pkgs/boots "$INSTALL_PKGS_DIR"
