#!/bin/sh
set -e

for type in "" "--release"; do
  # test serial minor & full collection
  cargo run $type -- --max-heap-size=512M --gc-verify bench/binarytrees/binarytrees.dora 21
  cargo run $type -- --max-heap-size=512M --gc-young-size=20M --gc-verify bench/binarytrees/binarytrees.dora 21

  # test alternative collectors
  cargo run $type -- --max-heap-size=1G --gc=copy bench/binarytrees/binarytrees.dora 21
  cargo run $type -- --max-heap-size=512M --gc=compact bench/binarytrees/binarytrees.dora 21

  # test parallel minor & full collection
  cargo run $type -- --max-heap-size=512M --gc-worker=4 --gc-verify --gc-parallel bench/binarytrees/binarytrees.dora 21
  cargo run $type -- --max-heap-size=512M --gc-worker=4 --gc-young-size=20M --gc-verify --gc-parallel bench/binarytrees/binarytrees.dora 21
done
