#!/bin/sh

set -e

cargo run -p dora -- test --package boots dora-boots/boots.dora --test-boots --gc-verify tests/hello-world.dora
cargo run -p dora -- --package boots dora-boots/boots.dora  --gc-verbose --emit-compiler --bootstrap-compiler tests/boots/hello.dora
ruby tools/tester.rb tests/boots
