#!/bin/sh

set -e

TARGET=x86_64-apple-darwin
cargo run -p dora --target $TARGET -- test dora-boots/boots.dora --gc-verify
cargo run -p dora --target $TARGET -- --package boots dora-boots/boots.dora  --gc-verbose --emit-compiler --bootstrap-compiler tests/boots/hello.dora
ruby tools/tester.rb  --target $TARGET tests/boots
