#!/bin/sh

set -e

cargo build --release
cargo test --release
cargo run -p dora --release -- --boots --report-all-warnings --gc-verbose --emit-compiler --bootstrap-compiler tests/boots/hello.dora
ruby tools/tester.rb --release $@
cargo run --release -p dora -- test --boots --test-boots tests/hello-world.dora
