use bytecode::generate::{BytecodeIdx, Register};

#[derive(PartialEq, Debug)]
pub enum Bytecode {
    Add(Register),
    BitwiseAnd(Register),
    BitwiseOr(Register),
    BitwiseXor(Register),
    Div(Register),
    Ldar(Register),
    LdaInt(u64),
    LdaZero,
    LdaTrue,
    LdaFalse,
    LogicalNot,
    Star(Register),
    JumpIfFalse(BytecodeIdx),
    Jump(BytecodeIdx),
    Mod(Register),
    Mul(Register),
    Neg,
    ShiftLeft(Register),
    ShiftRight(Register),
    ArithShiftRight(Register),
    Sub(Register),
    Return,
    ReturnVoid,
    TestEqual(Register),
    TestGreatherThan(Register),
    TestGreatherThanOrEqual(Register),
    TestLessThan(Register),
    TestLessThanOrEqual(Register),
    TestNotEqual(Register),
}
