use bytecode::generate::{BytecodeIdx, Register};

#[derive(PartialEq, Debug)]
pub enum Bytecode {
    AddInt(Register),
    AddLong(Register),
    AddFloat(Register),
    AddDouble(Register),
    AndInt(Register),
    OrInt(Register),
    XorInt(Register),
    DivInt(Register),
    Ldar(Register),
    LdaInt(u64),
    LdaZero,
    LdaTrue,
    LdaFalse,
    NotBool,
    Star(Register),
    JumpIfFalse(BytecodeIdx),
    JumpIfTrue(BytecodeIdx),
    Jump(BytecodeIdx),
    ModInt(Register),
    MulInt(Register),
    NegInt,
    ShlInt(Register),
    ShrInt(Register),
    SarInt(Register),
    SubInt(Register),
    Ret,
    RetVoid,
    TestEqInt(Register),
    TestEqPtr(Register),
    TestNeInt(Register),
    TestNePtr(Register),
    TestGtInt(Register),
    TestGeInt(Register),
    TestLtInt(Register),
    TestLeInt(Register),
}
