name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ fromJSON(matrix.timeout_minutes) }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            timeout_minutes: "90"
            test_config: all
          - os: ubuntu-24.04-arm
            timeout_minutes: "90"
            test_config: all
          - os: windows-latest
            timeout_minutes: "90"
            test_config: all
            msvc_arch: x64
          - os: windows-11-arm
            timeout_minutes: "180"
            test_config: all
            msvc_arch: arm64
          - os: macOS-latest
            timeout_minutes: "90"
            test_config: all

    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Clone Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Configure MSVC toolchain
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Verify MSVC toolchain
        if: runner.os == 'Windows'
        run: where.exe link

      - name: Verify Windows x64 assembler
        if: runner.os == 'Windows' && matrix.msvc_arch == 'x64'
        run: where.exe ml64

      - name: Verify Windows Arm64 assembler
        if: runner.os == 'Windows' && matrix.msvc_arch == 'arm64'
        run: |
          where.exe armasm64

      - name: Increase Stack Size
        shell: bash
        run: echo "RUST_MIN_STACK=16777216" >> "$GITHUB_ENV"

      - name: Test Release
        if: runner.os != 'Windows'
        run: tools/test -r -- --config ${{ matrix.test_config }}

      - name: Test Release (Windows)
        if: runner.os == 'Windows'
        run: .\tools\test -r -- --config ${{ matrix.test_config }}

      - name: Test
        if: runner.os != 'Windows'
        run: tools/test -- --config ${{ matrix.test_config }}

      - name: Test (Windows)
        if: runner.os == 'Windows'
        run: .\tools\test -- --config ${{ matrix.test_config }}
