name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macOS-latest]

    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Clone Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Configure MSVC toolchain
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Verify MSVC toolchain
        if: runner.os == 'Windows'
        run: |
          where.exe ml64
          where.exe link

      - name: Increase Stack Size
        run: echo "RUST_MIN_STACK=16777216" >> $GITHUB_ENV

      - name: Test Release
        if: matrix.os != 'windows-latest'
        run: tools/test -r -- --config all

      - name: Test Release (Windows)
        if: matrix.os == 'windows-latest'
        run: .\tools\test -r -- --config all

      - name: Test
        if: matrix.os != 'windows-latest'
        run: tools/test -- --config all

      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        run: .\tools\test -- --config all
