name: lint-and-test

on: [push, pull_request]

jobs:
  test:
    name: test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: "nightly"

      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Test
        if: matrix.os != 'windows-latest'
        run: tools/test

      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        run: .\tools\test.bat

      - name: Test Release
        if: matrix.os != 'windows-latest'
        run: tools/test-release

      - name: Test Release (Windows)
        if: matrix.os == 'windows-latest'
        run: .\tools\test-release.bat
